### PR TITLE
Subarrays support implementation

### PR DESCRIPTION
**Pull request by zonca**
Implement #11

### CODE REVIEW

**Comment by zonca** [comment]
@arunsurya77 I've completed the support for subarrays, would you like to review the pull request and provide feedback?

**Comment by arunsurya77** [comment]
Great I will check it out this week.

**Comment by zonca** [comment]
@arunsurya77 can you please provide feedback on this pull request?

**Comment by arunsurya77** [comment]
yes , Sorry about the delay. Will try to finish it tomorrow.

**Comment by arunsurya77** [comment]
Hi Andrea,

I posted this is in slack so probably you didn't see. Is there test data to
test subarrays. Also, I get this weird error when I try to run the tests
script.
pytest: error: unrecognized arguments: --current-env --nbval-lax
 inifile: /home/arun/asurya_dev/iris_pipeline_subarr/iris_pipeline/setup.cfg
 rootdir: /home/arun/asurya_dev/iris_pipeline_subarr/iris_pipeline11:24
What is the testing package used ?

Cheers
Arun

**Comment by zonca** [comment]
`nbval` https://github.com/computationalmodelling/nbval

**Comment by zonca** [comment]
added to the docs: e915162aa5ecb2f423c26832a9d5a38833547b69

**Comment by zonca** [comment]
@arunsurya77 I'll merge this, still if you send feedback I'll incorporate it later.

**Comment by arunsurya77** [comment]
Yes that works fine. I reviewed the code that day. But forgot to merge.

**Pull request merged**
